version: '3'
services:
  fastapi:
    build: ./app
    container_name: fastapi
    ports:
      - "8080:80"
    volumes:
      - ./app/:/app
    environment:
      - API_ENTRYPOINT = ${API_ENTRYPOINT}
    

